name: download_assets
description: Retrieve assets and add them to the application's repository for use.
version: 4.1.0
homepage: https://github.com/edjostenes/download_assets

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  path: ^1.9.1
  archive: ^4.0.7
  idb_shim: ^2.7.1+1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4

dev_dependencies:
  mocktail: ^1.0.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
