name: download_assets
description: Download and uncompress assets
version: 3.0.1
homepage: https://github.com/edjostenes/download_assets

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  path_provider: ^2.0.12
  archive: ^3.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: