name: download_assets
description: Retrieve assets and add them to the application's repository for use.
version: 3.1.1
homepage: https://github.com/edjostenes/download_assets

environment:
  sdk: '>=2.23.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  path: ^1.8.3
  archive: ^3.4.6
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: